
name: 'Exotel SMS'
author: 'Sagar Choudhary'
description: 'Send an SMS from GitHub Actions using Exotel SMS'
inputs:
  fromNumber:
    description: 'Exophone in your Exotel account to send the SMS from'
    required: true
  toNumber:
    description: 'Phone number to send the SMS to'
    required: true
  message:
    description: 'The message you want to send'
    required: true
  EXOTEL_ACCOUNT_SID:
    description: 'An Exotel Account SID. Can alternatively be stored in environment'
    required: true
  EXOTEL_API_KEY:
    description: 'An Exotel API Key. Can alternatively be stored in environment'
    required: true
  EXOTEL_API_TOKEN:
    description: 'An Exotel API Token. Can alternatively be stored in environment'
    required: true
outputs:
  smsMessageSid:
    description: 'The Exotel SmsMessage SID'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  color: 'blue'
  icon: 'message-circle'
